# Generated by Django 5.1.3 on 2024-11-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Red', models.BooleanField()),
                ('Green', models.BooleanField()),
                ('Blue', models.BooleanField()),
                ('distance', models.FloatField()),
            ],
        ),
    ]
